server:
  port: 8091

service:
  host:
    customer-module: http://localhost:8089
  url:
    customer_credit_card: "customers/{id}/credit_card"
  retry:
    max-attempts: 3
    backoff-in-seconds: 3

spring:
  datasource:
    url: jdbc:postgresql://kafka-docker:5432/payment_service
    username: admin
    password: No4Nooxip4qu
    driver_class_name: org.postgresql.Driver

rabbitmq:
  default:
    exchange: orderShopExchange
  queues:
    outbound:
      creditCardAuthorizedQueue:
        name: credit_card_authorized_queue
        routing-key: credit_card_authorized_queue
    inbound:
      creditCardAuthorizationQueue: credit_card_authorization_queue

hibernate:
  dialect: org.hibernate.dialect.PostgreSQL94Dialect
  format-sql: true
  show-sql: true
  naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy