server:
  port: 8089

spring:
  datasource:
    url: jdbc:postgresql://kafka-docker:5432/customer_serivce
    username: admin
    password: No4Nooxip4qu
    driver_class_name: org.postgresql.Driver


